### ISSUE TITLE
View, settings and toolbar are empty

### ISSUE THREAD

**Issue by Caceresenzo** [swdotcom/swdc-eclipse-codetime#11]
Hi,

I just installed the the plugin from the Eclipse's marketplace, but nothing seems to show up.

As you can see in the image bellow, the plugin's view does not seems to display anything. Even after restart.
![image](https://user-images.githubusercontent.com/7386242/98554601-30e00980-22a1-11eb-8af2-9aec88f2012d.png)

Also, when you click on the toolbar item, there is no menu showing up. (hard to show in a picture)

I am using Eclipse 2020-09, with JRE 11

**Comment by xavluiz** [comment]
Thank you for the issue update and the information details. We will look into this today and apologize for the inconvenience.
Regards.

**Comment by xavluiz** [comment]
Hi, my apologies on the issue. It is now resolved. We had an incorrect library reference within the build.properties file. I've also fixed the marketplace version listing to 2.2.22, but for some reason it still displayed as 2.2.14. The internal build version is 2.2.22 though. Here's a screenshot of the view after I installed it from the marketplace. Thank you so much for your patience and enjoy.
![Uploading Screen Shot 2020-11-10 at 6.24.34 AM.png…]()

**Comment by Caceresenzo** [comment]
Hi,

Thanks for your time.
I have done the update and can finally see the view.

But all of the sign up button does not work :/

Looking at the error log, I can see the following:

```
Command 'com.swdc.codetime.commands.metrics.login' failed
```

```
org.eclipse.core.commands.ExecutionException: Error executing 'com.swdc.codetime.commands.metrics.login': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4012)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3612)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 32 more
Caused by: java.lang.NullPointerException
	at java.base/java.net.URLEncoder.encode(URLEncoder.java:224)
	at java.base/java.net.URLEncoder.encode(URLEncoder.java:196)
	at com.swdc.codetime.util.SoftwareCoSessionManager.launchLogin(SoftwareCoSessionManager.java:314)
	at com.swdc.codetime.handlers.SoftwareLoginHandler.execute(SoftwareLoginHandler.java:15)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 36 more
```

```
eclipse.buildId=4.17.0.I20200902-1800
java.version=11.0.7
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/<hidden>/Developments/Workspace/ -product org.eclipse.epp.package.java.product
```

**Comment by Caceresenzo** [comment]
This is strange, I restarted the ide, and the button started to work.
But after login, nothing changed.

I was needed to restart the ide a second time.

**Comment by xavluiz** [comment]
I'll look at what is going on with this today, thank you for this update.

**Comment by xavluiz** [comment]
The stack trace was very helpful, thank you. It seems the token was null and encoding failed. I've updated the updatesite with the new build: v2.2.23

I've tested the lifecycle it worked without issues but let us know if there are any other issues, thanks again.
